import { existsSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const apiDocsDirectoryPath = resolve(
    fileURLToPath(new URL("./site-docs/developer/api", import.meta.url))
);

const hasGeneratedApiDocs = (() => {
    if (!existsSync(apiDocsDirectoryPath)) {
        return false;
    }

    return readdirSync(apiDocsDirectoryPath, { recursive: true }).some(
        (entryName) => /\.(?:md|mdx)$/u.test(String(entryName))
    );
})();

const sidebars = {
    docs: [
        {
            className: "sb-cat-developer",
            id: "developer/index",
            label: "Developer Docs",
            type: "doc",
        },
        {
            className: "sb-doc-site-contract",
            id: "developer/docusaurus-site-contract",
            label: "Docs Site Contract",
            type: "doc",
        },
        ...(hasGeneratedApiDocs
            ? [
                  {
                      className: "sb-cat-api-runtime",
                      collapsed: true,
                      items: [
                          {
                              dirName: "developer/api",
                              type: "autogenerated" as const,
                          },
                      ],
                      label: "API",
                      type: "category" as const,
                  },
              ]
            : []),
    ],
} satisfies SidebarsConfig;

export default sidebars;
